service: my-python-service
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
functions:
  function1:
    handler: functions/function1/handler.handler
  function2:
    handler: functions/function2/handler.handler
  function3:
    handler: functions/function3/handler.handler
