service: my-python-service1
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
functions:
  function1:
    handler: handler.handler
    events:
      - http:
          path: function1
          method: GET
      - http:
          path: function1
          method: POST
  function2:
    handler: handler.handler
    events:
      - http:
          path: function2
          method: GET
      - http:
          path: function2
          method: POST
  function3:
    handler: handler.handler
    events:
      - http:
          path: function3
          method: GET
      - http:
          path: function3
          method: POST
