name: "Deploy SAM to AWS"
on: 
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maximilianobz/actions-samdeploy@v1.0.4
      env:
        AWS_REGION: 'ap-south-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    - name: deploy service
      run: sam deploy --config-env $SAM_ENV
   
